export const blendModeOptions = [
    { value: "normal", label: "Normal" },
    { value: "multiply", label: "Multiplicar" },
    { value: "screen", label: "Pantalla" },
    { value: "overlay", label: "Superponer" },
    { value: "darken", label: "Oscurecer" },
    { value: "lighten", label: "Aclarar" },
    { value: "color-dodge", label: "Aclarar color" },
    { value: "color-burn", label: "Oscurecer color" },
    { value: "hard-light", label: "Luz dura" },
    { value: "soft-light", label: "Luz suave" },
    { value: "difference", label: "Diferencia" },
    { value: "exclusion", label: "Exclusión" },
    { value: "hue", label: "Tono" },
    { value: "saturation", label: "Saturación" },
    { value: "color", label: "Color" },
    { value: "luminosity", label: "Luminosidad" },
];
