export const imageMasks = [
    {
        id: "none",
        name: "Sin máscara",
        class: "",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4" />,
    },
    {
        id: "circle",
        name: "Círculo",
        class: "mask-circle",
        category: "Básicas",
        //icon: () => <Circle className="h-4 w-4" />,
    },
    {
        id: "rounded",
        name: "Redondeado",
        class: "mask-rounded",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4 rounded-md" />,
    },

    {
        id: "star",
        name: "Estrella",
        class: "mask-star-2",
        category: "Formas",
        //icon: () => <Star className="h-4 w-4" />,
    },
    {
        id: "hexagon",
        name: "Hexágono",
        class: "mask-hexagon",
        category: "Formas",
        //icon: () => <Hexagon className="h-4 w-4" />,
    },
    {
        id: "triangle",
        name: "Triángulo",
        class: "mask-triangle",
        category: "Formas",
        //icon: () => <div className="w-4 h-4 bg-current clip-triangle" />,
    },
    {
        id: "diamond",
        name: "Diamante",
        class: "mask-diamond",
        category: "Formas",
        //icon: () => <Diamond className="h-4 w-4" />,
    },
    {
        id: "polaroid",
        name: "Polaroid",
        class: "mask-polaroid",
        category: "Fotográficos",
        //icon: () => <Film className="h-4 w-4" />,
    },
    {
        id: "vintage",
        name: "Vintage",
        class: "mask-vintage",
        category: "Fotográficos",
        //icon: () => <Feather className="h-4 w-4" />,
    },

    {
        id: "diagonal",
        name: "Diagonal",
        class: "mask-diagonal",
        category: "Fotográficos",
        //icon: () => <div className="w-4 h-4 bg-current clip-diagonal" />,
    },
    {
        id: "frame",
        name: "Marco",
        class: "mask-frame",
        category: "Fotográficos",
        //icon: () => <Square className="h-4 w-4" />,
    },

    {
        id: "blob1",
        name: "Mancha 1",
        class: "mask-blob1",
        category: "Creativas",
        //icon: () => <div className="w-4 h-4 bg-current rounded-full" />,
    },
    {
        id: "blob2",
        name: "Mancha 2",
        class: "mask-blob2",
        category: "Creativas",
        //icon: () => <div className="w-4 h-4 bg-current rounded-full" />,
    },
    {
        id: "blob3",
        name: "Mancha 3",
        class: "mask-blob3",
        category: "Creativas",
        //icon: () => <div className="w-4 h-4 bg-current rounded-full" />,
    },
    {
        id: "rounded-sm",
        name: "Redondeado pequeño",
        class: "mask-rounded-sm",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4 rounded-sm" />,
    },
    {
        id: "rounded-lg",
        name: "Redondeado grande",
        class: "mask-rounded-lg",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4 rounded-lg" />,
    },

    {
        id: "speech",
        name: "Globo de texto",
        class: "mask-speech",
        category: "Formas",
        //icon: () => <div className="w-4 h-4 bg-current clip-speech" />,
    },
    {
        id: "burst",
        name: "Estallido",
        class: "mask-burst",
        category: "Formas",
        //icon: () => <Zap className="h-4 w-4" />,
    },
    {
        id: "rounded-rect",
        name: "Rectángulo redondeado",
        class: "mask-rounded-rect",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4 rounded-md" />,
    },
];
